project_id = "zwoyfgqepikiuszxuqjg"

[functions.check-registration]
verify_jwt = false

[functions.change-user-password]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.delete-user]
verify_jwt = false

[functions.toggle-user-access]
verify_jwt = false

[functions.validate-share-token]
verify_jwt = false